FROM node:22.11

# Set working directory
WORKDIR /frontend

# Copy only package.json and package-lock.json first
# COPY ./frontend/package.json .
# COPY ./frontend/package-lock.json .

# Install dependencies
# RUN npm install

# Now copy the rest of your frontend code
COPY ./frontend .

# Expose port if needed (optional, e.g., if you use Vite/Next.js/etc.)
# EXPOSE 3000

# Start the app
CMD ["npm", "run", "build"]
