# Generated by Django 5.2.2 on 2025-06-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
