# Generated by Django 5.2.4 on 2025-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredient_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientalldata',
            name='contains_allergens',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='core.allergy'),
        ),
        migrations.AddField(
            model_name='ingredientalldata',
            name='dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='core.dietarypreference'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='contains_allergens',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='core.allergy'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='suitable_for_diets',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='core.dietarypreference'),
        ),
    ]
