# Generated by Django 5.2.4 on 2025-07-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredientalldata_contains_allergens_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientalldata',
            options={'ordering': ['name'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_preferences',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dietarypreference'),
        ),
    ]
