# Generated by Django 5.2.4 on 2025-07-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ingredientalldata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='items',
            field=models.ManyToManyField(through='core.ShoppingListItem', to='core.ingredientalldata'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredientalldata'),
        ),
    ]
