# Generated by Django 5.2.4 on 2025-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_meal_date_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dietarypreference',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
